### GET /
GET http://localhost:9001/

### Get a value
POST http://localhost:9001/
Content-Type: application/json 

{
  "action": "get",
  "key": "foobar"
}

### POST /
POST http://localhost:9001/
Content-Type: application/json 

{
  "action": "set",
  "key": "foobar",
  "value": "some value 3"
}

### DELETE /
POST http://localhost:9001/
Content-Type: application/json 

{
  "action": "del",
  "key": "foobar"
}

### POST /init
POST http://localhost:9001/
Content-Type: application/json 

{
  "action": "init"
}